from django.urls import path
from . import views
from .views import agregar_rol,login_view,admin_dashboard, user_dashboard,logout_view,agregar_proyecto,detalles_proyecto,insertar_usuario,mi_vista, verificar_nombre_proyecto,verificar_nombre_fase

urlpatterns = [
    path('', views.mi_vista, name='mostrar_base_datos'),
    path('mostrar-base-datos/', views.mostrar_base_datos, name='mostrar_base_datos'),
    path('agregar-rol/', views.agregar_rol, name='agregar_rol'),
    path('logout/', views.logout_view, name='logout'),
    path('login/', views.login_view, name='login'),
    path('admin_dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('admin_dashboard/detalles-proyecto/<int:proyecto_id>/', views.detalles_proyecto, name='detalles_proyecto'),
    path('user_dashboard/', views.user_dashboard, name='user_dashboard'),
    path('agregar_proyecto/', views.agregar_proyecto, name='agregar_proyecto'),
    path('registrar_usuario/', views.registrar_usuario, name='registrar_usuario'),
    path('insertar_usuario/', views.insertar_usuario, name='insertar_usuario'),
    path('proyecto/<int:proyecto_id>/agregar-fase/', views.agregar_fase, name='agregar_fase'),
    path('proyecto/<int:proyecto_id>/asignar-recurso-humano/', views.asignar_recurso_humano, name='asignar_recurso_humano'),
    path('proyecto/<int:proyecto_id>/agregar-recurso-material/', views.agregar_recurso_material, name='agregar_recurso_material'),
    path('proyecto/<int:proyecto_id>/agregar-documento/', views.agregar_documento, name='agregar_documento'),
    path('proyecto/<int:proyecto_id>/agregar-riesgo/', views.agregar_riesgo, name='agregar_riesgo'),
    path('editar_proyecto/<int:proyecto_id>/', views.editar_proyecto, name='editar_proyecto'),
    path('prioridades/', views.dashboard_prioridades, name='dashboard_prioridades'),
    path('prioridades/actualizar/', views.actualizar_prioridades_view, name='actualizar_prioridades'),
    path('prioridades/proyecto/<int:proyecto_id>/', views.detalle_prioridad_proyecto, name='detalle_prioridad_proyecto'),
    path('proyecto/<int:proyecto_id>/eliminar/', views.eliminar_proyecto, name='eliminar_proyecto'),
    path('proyecto/<int:proyecto_id>/agregar-tarea/', views.agregar_tarea, name='agregar_tarea'),
    path('relacion-documento/<int:relacion_id>/marcar-concluido/', views.marcar_entregable_concluido, name='marcar_entregable_concluido'),
    path('relacion-documento/<int:relacion_id>/desmarcar-concluido/', views.desmarcar_entregable_concluido, name='desmarcar_entregable_concluido'),
    path('fase/<int:fase_id>/marcar-concluida/', views.marcar_fase_concluida, name='marcar_fase_concluida'),
    path('fase/<int:fase_id>/desmarcar-concluida/', views.desmarcar_fase_concluida, name='desmarcar_fase_concluida'),
    path('verificar-nombre-proyecto/', views.verificar_nombre_proyecto, name='verificar_nombre_proyecto'),
    path('verificar-disponibilidad-usuario/', views.verificar_disponibilidad_usuario, name='verificar_disponibilidad_usuario'),
    path('proyecto/<int:proyecto_id>/finalizar/', views.finalizar_proyecto, name='finalizar_proyecto'),
    path('proyecto/<int:proyecto_id>/reactivar/', views.reactivar_proyecto, name='reactivar_proyecto'),
    path('recurso-humano/<int:recurso_humano_id>/eliminar/', views.eliminar_recurso_humano, name='eliminar_recurso_humano'),
    path('gestion-recursos-humanos/', views.gestion_recursos_humanos, name='gestion_recursos_humanos'),
    path('recurso-humano/<int:usuario_id>/editar/', views.editar_recurso_humano, name='editar_recurso_humano'),
    path('usuario/<int:usuario_id>/eliminar/', views.eliminar_usuario, name='eliminar_usuario'),
    path('proyecto/<int:proyecto_id>/agregar-tarea/', views.agregar_tarea, name='agregar_tarea'),
    path('validar-fecha-tarea/', views.validar_fecha_tarea, name='validar_fecha_tarea'),
    path('verificar-nombre-fase/', views.verificar_nombre_fase, name='verificar_nombre_fase'),
    path('proyecto/<int:proyecto_id>/agregar-tarea/', views.agregar_tarea, name='agregar_tarea'),

]