# Generated by Django 5.2.7 on 2025-10-20 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applogin', '0005_relaciondocumento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'ordering': ['-prioridad_score', 'fecha_final']},
        ),
        migrations.AddField(
            model_name='proyecto',
            name='prioridad_nivel',
            field=models.CharField(choices=[('Crítica', 'Crítica'), ('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], default='Media', max_length=20),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='prioridad_score',
            field=models.FloatField(default=0.0, help_text='Puntuación de prioridad calculada automáticamente'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='ultima_actualizacion_prioridad',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
