# Generated by Django 5.2.7 on 2025-10-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applogin', '0006_alter_proyecto_options_proyecto_prioridad_nivel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='archivo_documento',
            field=models.FileField(blank=True, help_text='Archivo PDF (máximo 15MB)', null=True, upload_to='documentos/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='url_documento',
            field=models.URLField(blank=True, null=True),
        ),
    ]
