# Generated by Django 5.2.7 on 2025-10-29 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applogin', '0007_documento_archivo_documento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(help_text='Descripción de la tarea o actividad a realizar')),
                ('fecha_limite', models.DateField(help_text='Fecha límite para completar la tarea')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Progreso', 'En Progreso'), ('Completada', 'Completada')], default='Pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('documento_entregable', models.ForeignKey(blank=True, help_text='Documento entregable subido por el recurso humano', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarea_relacionada', to='applogin.documento')),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='applogin.fase')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='applogin.proyecto')),
                ('recurso_humano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='applogin.recursohumano')),
            ],
            options={
                'ordering': ['fecha_limite', 'estado'],
            },
        ),
    ]
