# Generated by Django 5.2.7 on 2025-10-29 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applogin', '0008_tarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='relaciondocumento',
            name='concluido',
            field=models.BooleanField(default=False, help_text='Indica si el entregable ha sido aprobado y concluido'),
        ),
        migrations.AddField(
            model_name='relaciondocumento',
            name='fecha_conclusion',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se marcó como concluido', null=True),
        ),
    ]
