# Generated by Django 5.2.7 on 2025-10-30 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applogin', '0009_relaciondocumento_concluido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(default='En proceso', max_length=50),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='nombre_proyecto',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
