# Generated by Django 5.2.7 on 2025-10-30 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applogin', '0010_alter_proyecto_estado_alter_proyecto_nombre_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='nombre_proyecto',
            field=models.CharField(max_length=100),
        ),
    ]
