# Generated by Django 5.2.7 on 2025-10-30 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applogin', '0011_alter_proyecto_nombre_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(blank=True, default='En proceso', max_length=50),
        ),
    ]
