# Generated by Django 5.2.7 on 2025-10-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applogin', '0012_alter_proyecto_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='fecha_finalizacion',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se finalizó el proyecto', null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='finalizado',
            field=models.BooleanField(default=False, help_text='Indica si el proyecto ha sido finalizado'),
        ),
    ]
