# Generated by Django 5.2.7 on 2025-11-08 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applogin', '0013_proyecto_fecha_finalizacion_proyecto_finalizado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fase',
            options={'verbose_name': 'Fase', 'verbose_name_plural': 'Fases'},
        ),
        migrations.AlterField(
            model_name='fase',
            name='concluido',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='fase',
            unique_together={('proyecto', 'fase')},
        ),
    ]
