# Generated by Django 5.2.7 on 2025-12-08 00:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applogin', '0014_alter_fase_options_alter_fase_concluido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='archivo_documento',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Archivo PDF (máximo 15MB)', max_length=255, null=True, verbose_name='documento'),
        ),
    ]
